# Generated by Django 5.1 on 2024-08-15 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(unique=True)),
                ('stop_time', models.DateTimeField()),
                ('status', models.CharField(max_length=45)),
                ('csv_filename', models.CharField(max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
