# Generated by Django 5.1 on 2024-09-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_scanrecord_user_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
