# Generated by Django 5.1 on 2024-09-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alert_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='message_status',
            field=models.CharField(default='Normal', max_length=20),
        ),
    ]
